language: java
arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - export BUILD_TAG="20210528"
script: 
  - export pwd=$PWD && echo $PWD
  - docker build . -f Dockerfile -t toyangdon/mysql-operator:$(BUILD_TAG)
  - docker build . -f Dockerfile.orchestrator -t toyangdon/orchestrator:$(BUILD_TAG)
  - docker build . -f Dockerfile.sidecar -t toyangdon/mysql-helper:$(BUILD_TAG)
  - docker push toyangdon/mysql-operator:$(BUILD_TAG)
  - docker push toyangdon/orchestrator:$(BUILD_TAG)
  - docker push toyangdon/mysql-helper:$(BUILD_TAG)
